### ISSUE TITLE
Get time of ingestion of new data in pyniva

### ISSUE THREAD

**Issue by ZofiaRudjord** [NIVANorge/pyniva#23]
Request from @nivapja to be able to get time of ingestion of data.

*Usage*:
- check which data are new for exporting to third party
- define harbours

*Proposed solution*

Signature would be of the type:
[(Boat, start_time_measurement, end_time_measurement)] = get_ingestion_time(Boat, start_time, end_time)
where (start_time, end_time) would be time interval of interest (e.g. lats month)
and (start_time_measurement, end_time_measurement) would denote start and end time of fb measurements.

This information can be extracted from stream metadata. Signal_status table contains information on json_file_path and create_time. json_file_path encodes start_time_measurement, end_time_measurement).

Warning: json_file_path signature did not always encoded start_time_measurement, end_time_measurement so this solution will work from now on and not backward compatible.

**Comment by haakondr** [comment]
Summarised discussion with Zofia:

I am afraid that the proposed solution  to use stream metadata could be a bit fragile. 

## Main concerns:

- we are adding **two** new  system dependencies to ms-ferrybox, more moving parts (ms-ferrybox needs to understand error handling of yet another API, more chances of latency++)
  - ms-ferrybox would need to rely on both stream-metadata and cloud storage in order to figure out measurement paths
- We could get the list of signal_status inserted within a timespan, but we don't have a direct link between the signal and tsb rows (we do have measurement timespan in the json files, but that would require us to download the file on each request)
- this may seem easy in case of chronological ingestion, but what about in cases where a file has been stuck, and then ingested some weeks later. What would get_ingestion_time return?
  - I think we need to increase the granularity of the data, and actually return new data since time x.

## alternative solutions

- add insert/update time to tsb ts columns?
  - What would be the extra storage requirement to do this? 
  - IMO easiest solution, code wise
- establish a second table in tsb holding this data?
  - Pros: we could do this per signal instead of per measurement
  - cons: more code changes involved, may not be very practical
- establish a streaming solution where pyniva subscribers subscribe to their own stream of data? 
  - this way we hold state about consumption progress serverside. e.g. copernicus sync has 55 new measurements that are not acked. This is perhaps the ideal solution in my eyes, but probably not feasible in the short term as it is a big step forward in terms of how we consume and sync data

**Comment by ZofiaRudjord** [comment]
I  am not convinced we need precision to that extend as to download the file.
I *think* we could provide data that were either created or updated in the given time span,
I will ask @nivapja  about it.
